name: GCP Artifact Registry Auth
description: Setup gcloud and register it as a Docker credential helper for the specificied GCP Artifact Registry
inputs:
  gcp-sa-creds-json:
    description: The Google Cloud JSON service account key to use for authentication
    required: true
  registry:
    description: GCP Artifact Registry
    required: true
    default: europe-west3-docker.pkg.dev
runs:
  using: composite
  steps:
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcp-sa-creds-json }}
    - name: Setup GCP SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
    - name: Configure Docker Client
      shell: bash
      run: gcloud --quiet auth configure-docker ${{ inputs.registry }}
